#!/bin/sh

# Create a new page for the website from the Markdown sample page using Vim.

if [ -z "$1" ]; then
    echo 'Error: no file name given.' 2>&1
    exit 1
fi

uuid="$(uuidgen | tr '[A-Z]' '[a-z]')"

"$EDITOR" 'ssg/sample.md' +"f $1" +"2s/UUID/$uuid/"
