name: Build website
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build website
    env:
      CLOUDFRONT_DIST_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: '1.10.3.1029'

      - name: Build website
        run: clojure -X:build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to S3
        run: |
          # delete old files and upload files from local directory to s3 bucket and set the cache control header on every single file.
          aws s3 sync ./resources/dist/ "$S3_BUCKET" \
            --delete \
            --cache-control 'max-age=604800'
          # Shorten Cache-Control for HTML files.
          aws s3 cp "$S3_BUCKET" "$S3_BUCKET" \
            --recursive \
            --exclude '*' \
            --include '*.html' \
            --copy-props 'metadata-directive' \
            --content-type 'text/html'
          # Set Content-Type for font files.
          aws s3 cp "$S3_BUCKET" "$S3_BUCKET" \
            --recursive \
            --exclude '*' \
            --include '*.woff' \
            --copy-props 'metadata-directive' \
            --content-type 'font/woff'
          aws s3 cp "$S3_BUCKET" "$S3_BUCKET" \
            --recursive \
            --exclude '*' \
            --include '*.woff2' \
            --copy-props 'metadata-directive' \
            --content-type 'font/woff2'

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_DIST_ID" \
            --paths '/*'
