name: Deploy website
on: [push, workflow_dispatch]

jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.2
        with:
          lfs: true

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.2.1446

      - name: Build website
        run: |
          git fetch origin dist --depth=1
          git worktree add dist origin/dist
          git -C dist rm -r .
          clojure -X:build
          cp -r resources/dist/* dist/

      - name: Deploy changes
        uses: EndBug/add-and-commit@v7
        with:
          cwd: dist/
          branch: dist
          default_author: github_actions
          message: Deploy website
          add: '*'

      - name: Clean up
        run: git worktree remove --force dist
