name: Deploy website
on: [push, workflow_dispatch]

jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          lfs: true

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.12.0.1488

      - name: Build website
        run: |
          git fetch origin dist --depth=1
          git worktree add dist origin/dist
          git -C dist rm -r .
          clojure -X:build
          cp -r target/website/* dist/

      - name: Deploy changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          cwd: dist/
          default_author: github_actions
          message: Deploy website
          add: '*'

      - name: Clean up
        run: git worktree remove --force dist
