name: Deploy website
on: [push, workflow_dispatch]

jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: '1.12.1.1550'

      - name: Build website
        run: |
          do/build
          git fetch origin dist --depth=1
          git worktree add dist origin/dist
          git -C dist rm -r .
          cp -r .dist/* dist/

      - name: Deploy changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: dist/
          new_branch: dist
          default_author: github_actions
          message: Deploy website
          add: '*'

      - name: Clean up
        run: git worktree remove --force dist
